### ISSUE TITLE
Unable to install freeswitch plugin

### ISSUE THREAD

**Issue by ChandanPR** [kjhosein/nagios-freeswitch-plugin#3]
Looks like the Nagios plugin moved to monitoring. I have installed the Monitoring plugin using perl -MCPAN -e 'install Monitoring::Plugin'

Is there any instructions available on how to install the freeswitch plugin?

Thanks,
Chandan

**Comment by kjhosein** [comment]
Have you read the [README](https://github.com/kjhosein/nagios-freeswitch-plugin)?

**Comment by ChandanPR** [comment]
Have gone through the READ ME and was having difficulties in installing the nagios plugin modules. Then some posts on SFO were suggesting it has been moved to Monitoring plugin. Will try again.
