### ISSUE TITLE
Use with Sangoma NSG FreeSwitch

### ISSUE THREAD

**Issue by richilp** [kjhosein/nagios-freeswitch-plugin#4]
Hello there,

we've modify a little bit the plugin to check Freeswitch in Sangoma NSG devices.

CHANGES:

> # Fully qualified path to fs_cli. Modify this to suit:
> `my $fs_cli_location = "/usr/local/nsg/bin/nsg_cli";`
> 
> # Currently processed fs_cli queries:
> ```
> my @allowed_checks = (
>     "show calls",
```
> 
> # Perform a 'show calls'
>      when ( "show calls" ) {
>              @fs_cli_output = `$fs_cli_location -x "show calls"`;
>                      foreach ( @fs_cli_output ) {
>                                  if ( /total/i ) {
>                                         my @temp = split( /\s+/, $_ );
>                                         $rawdata = $_;
>                                         $result  = $temp[0];
>                                         last;
>                                  }
>                      }
>         }

That way works perfect win the NSG cli command

**Comment by kjhosein** [comment]
Hello @richilp  - sorry for the slight delay in responding ;-) 

Thanks for the addition. So as not to make the code more complex, I've simply created a new branch `sangoma_nsg` with your modifications for these particular devices. Please take a look and let me know if it looks ok. 
Thanks!
