### ISSUE TITLE
configuration question

### ISSUE THREAD

**Issue by Spyder13337** [kjhosein/nagios-freeswitch-plugin#6]
I know it be a while since I use nagios but I am not sure it config properly perhaps you can give me a quick look over 

I also change the file name from check_freeswitch_health to check_freeswitch 
also changed the name in your script as well but nothing else 

Serverside : 
nrpe.cfg 
command[check_freeswitch]=/usr/local/nagios/libexec/check_freeswitch  -q show-calls-count

command.cfg 

# 'check_freeswtich' command definition
 define command{
    command_name    check_freeswitch
    command_line    $USER1$/check_freeswitch -H $HOSTADDRESS$ -c $ARG1$ -a $ARG2$

service.cfg 

define service {
        use                             generic-service
        service_description             FreeSWITCH Call Count
        check_command                   check_freeswitch! -q show-calls-count

Client : 
nope.cfg
command[check_freeswitch]=/usr/local/nagios/libexec/check_freeswitch -q show-calls-count

**Comment by kjhosein** [comment]
Unless you have a hard requirement to change the filename, I would recommend against doing that. It just increases the possibility of errors. For example, there are multiple errors in your configs.

**Comment by Spyder13337** [comment]
I just want to conform with the other plugin that are named check_XXXX that all where do you see the error
