### ISSUE TITLE
issue with centos 7

### ISSUE THREAD

**Issue by Spyder13337** [kjhosein/nagios-freeswitch-plugin#7]
i have the config working properly for debian  8 but for centos 7 is just does not return any data als i have disabled centos 7 selinux and rebooted 

## nrpe.cg 
dont_blame_nrpe=1
command[check_freeswitch]=/usr/local/nagios/libexec/check_freeswitch $ARG1$

## Service.cfg 

define service {
        use                             generic-service
        service_description             FreeSWITCH Call Count
        check_command                   check_freeswitch!-a '-q show-calls-count'!!!!!!!
        max_check_attempts              3
        check_interval                  5
        retry_interval                  1
        check_period                    24x7
        notification_interval           60
        notification_period             24x7
        servicegroups                   FS Call Count
        hostgroups                      LCR,Mantis
        contacts                        nagiosadmin

## Command.cfg 

 define command {
    command_name    check_freeswitch
    command_line    $USER1$/check_nrpe -H $HOSTADDRESS$ -c check_freeswitch $ARG1$
  }

### Remote server 

nrpe.cfg 

i also enable dont_blame_nrpe=1 and conffiguere with --enable-command-args in nrpe vers 3.21 

command[check_freeswitch]=/usr/local/nagios/libexec/check_freeswitch $ARG1$ 

any help woudl be awesome

**Comment by kjhosein** [comment]
Hello - sorry for the late response, and I hope you've resolved this by this point! 

Unfortunately, I don't currently have a Nagios+Freeswitch dev/test environment to further test. However, I was using this plugin with CentOS 6.x and 7.x, and don't believe there are any CentOS-specific reasons why it wouldn't work.

**Comment by Spyder13337** [comment]
Sorry for the long response as well


But yeah it still not working on centos 7 can you possible send me your config files ti compare it to mines I know if I run the command manually It works but if I run it via nrpe it just return nothing as the result are not there I see no error that I am aware of the result retune 0 that al it quite strange some version on detain 8 or 9 I can’t recall and everything works fine the right result are showned

**Comment by kjhosein** [comment]
Hello @Spyder13337 - Unfortunately, that was a few years back, and I don't have those configs any more.

How 'stock' is your CentOS box? Could you potentially stand up a 'clean' CentOS 7 install and test it there?

Sorry I only have suggestions, and not solid answers, but I currently don't work in a FreeSwitch + Nagios environment.
